buildscript {
  repositories {
    mavenCentral()
    gradlePluginPortal()
    maven { url = 'https://s01.oss.sonatype.org' }
    mavenLocal()
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
    maven { url = 'https://oss.sonatype.org/content/repositories/releases/' }
  }
  dependencies {
  }
}

allprojects {
  apply plugin: 'eclipse'
  apply plugin: 'idea'

  version = projectVersion
  ext.appName = rootProject.appName

  repositories {
    mavenCentral()
    maven { url = 'https://s01.oss.sonatype.org' }
    mavenLocal()
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
    maven { url = 'https://oss.sonatype.org/content/repositories/releases/' }
    maven { url = 'https://jitpack.io' }
  }
}

eclipse.project.name = appName + '-parent'
